Traceback (most recent call last):
  File "02_acquire_app_info.py", line 67, in validate_parsed_data
    try:
AssertionError: details success is false
